project_name: languagetool-lint
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
builds:
  - main: .
    ldflags:
      - -s -w
      - -X github.com/skanehira/languagetool-lint/cmd.Version={{.Version}}
      - -X github.com/skanehira/languagetool-lint/cmd.Revision={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
